"use client";
import {useEffect, useState, useRef} from "react";
import {BarChart, Bar, PieChart, Pie, Cell, ResponsiveContainer, Tooltip} from "recharts";
type Expense={id:number;amount:number;currency:string;category:string;description:string;spent_at:string};
const API=process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";
const colors=["#2563eb","#7c3aed","#db2777","#ea580c","#16a34a","#64748b"];
export default function Home(){
 const [token,setToken]=useState(""); const [items,setItems]=useState<Expense[]>([]); const [summary,setSummary]=useState<Record<string,number>>({}); const [breakdown,setBreakdown]=useState<{days:any[];categories:any[]}>({days:[],categories:[]}); const [form,setForm]=useState({amount:"",description:"",category:"Другое"});
 const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const pending=useRef(false);
 const headers=()=>({Authorization:`tma ${token}`,"Content-Type":"application/json"});
 async function request(path:string, options:RequestInit={}) {
  const r=await fetch(`${API}${path}`,{...options,headers:headers()});
  if(r.status===401){setToken("");throw new Error("Срок входа истёк. Войдите через Telegram снова.")}
  if(!r.ok)throw new Error(r.status===422?"Проверьте сумму и описание.":"Сервер не подтвердил операцию. Обновите список перед повтором.");
  return r;
 }
 async function load(){if(!token)return;try{const responses=await Promise.all([request("/expenses"),request("/reports/summary"),request("/reports/breakdown")]);const [a,b,c]=await Promise.all(responses.map(r=>r.json()));setItems(a);setSummary(b);setBreakdown(c);setError("")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить расходы.")}}
 useEffect(()=>{try{const saved=sessionStorage.getItem("expense-login");if(saved)setToken(saved)}catch{}},[]);
 useEffect(()=>{try{if(token)sessionStorage.setItem("expense-login",token);else sessionStorage.removeItem("expense-login")}catch{};setItems([]);setSummary({});setBreakdown({days:[],categories:[]});load()},[token]);
 async function action(fn:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError("");try{await fn()}catch(e){setError(e instanceof Error?e.message:"Ошибка связи. Проверьте список перед повтором.")}finally{pending.current=false;setBusy(false)}}
 async function add(e:React.FormEvent){e.preventDefault();await action(async()=>{await request("/expenses",{method:"POST",body:JSON.stringify({...form,amount:form.amount.replace(",",".")})});setForm({amount:"",description:"",category:"Другое"});await load()})}
 async function remove(id:number){if(confirm("Удалить эту трату?"))await action(async()=>{await request(`/expenses/item/${id}`,{method:"DELETE"});await load()})}
 async function edit(x:Expense){const amount=prompt("Сумма",String(x.amount));if(amount===null)return;const description=prompt("Описание",x.description);if(description===null)return;const category=prompt("Категория",x.category);if(category===null)return;await action(async()=>{await request(`/expenses/item/${x.id}`,{method:"PUT",body:JSON.stringify({amount:amount.replace(",","."),description,category,currency:x.currency,spent_at:x.spent_at})});await load()})}
 async function downloadCsv(){await action(async()=>{const r=await request("/expenses/export/csv");const url=URL.createObjectURL(await r.blob());const a=document.createElement("a");a.href=url;a.download="expenses.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)})}
 if(!token)return <main className="auth"><h1>Мои расходы</h1><p>Войдите через Telegram — отдельный пароль не нужен.</p>{error&&<p role="alert">{error}</p>}<TelegramLogin onAuth={setToken}/></main>;
 return <main aria-busy={busy}>{error&&<p role="alert">{error} <button onClick={()=>load()}>Обновить</button></p>}<header><div><h1>Мои расходы</h1><p>Ваш личный бюджет</p></div><button onClick={()=>setToken("")}>Выйти</button></header><section className="cards">{[["Сегодня",summary.today],["Неделя",summary.week],["Месяц",summary.month]].map(([k,v])=><article key={String(k)}><span>{k}</span><strong>{Number(v||0).toFixed(2)} TJS</strong></article>)}</section><section className="grid"><form onSubmit={add}><h2>Новая трата</h2><input required inputMode="decimal" placeholder="Сумма" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><input required placeholder="Описание" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["Другое","Еда","Транспорт","Дом","Здоровье","Покупки"].map(x=><option key={x}>{x}</option>)}</select><button disabled={busy}>{busy?"Сохранение…":"Добавить"}</button></form><article className="chart"><h2>По дням</h2><ResponsiveContainer width="100%" height={220}><BarChart data={breakdown.days}><Tooltip/><Bar dataKey="amount" fill="#2563eb" radius={6}/></BarChart></ResponsiveContainer></article><article className="chart"><h2>По категориям</h2><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={breakdown.categories} dataKey="amount" nameKey="category" outerRadius={80}>{breakdown.categories.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></article></section><section className="list"><div className="sectionHead"><h2>Все расходы</h2><button disabled={busy} onClick={downloadCsv}>CSV</button></div>{items.length===0&&<p>Трат пока нет.</p>}{items.map(x=><article key={x.id}><div><strong>{x.description}</strong><span>{new Date(x.spent_at).toLocaleDateString("ru-RU")} · {x.category}</span></div><b>{x.amount} {x.currency}</b><button onClick={()=>edit(x)}>Изм.</button><button aria-label="Удалить" onClick={()=>remove(x.id)}>×</button></article>)}</section></main>
}
function TelegramLogin({onAuth}:{onAuth:(token:string)=>void}){useEffect(()=>{(window as any).onTelegramAuth=(user:any)=>onAuth(new URLSearchParams(Object.entries(user).map(([k,v])=>[k,String(v)])).toString());const s=document.createElement("script");s.src="https://telegram.org/js/telegram-widget.js?22";s.async=true;s.setAttribute("data-telegram-login",process.env.NEXT_PUBLIC_TELEGRAM_BOT_USERNAME||"");s.setAttribute("data-size","large");s.setAttribute("data-onauth","onTelegramAuth(user)");document.getElementById("telegram-login")?.appendChild(s);return()=>s.remove()},[onAuth]);return <div id="telegram-login"/>}
