"use client";
import {useEffect, useState} from "react";
import {BarChart, Bar, PieChart, Pie, Cell, ResponsiveContainer, Tooltip} from "recharts";
type Expense={id:number;amount:number;currency:string;category:string;description:string;spent_at:string};
const API=process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";
const colors=["#2563eb","#7c3aed","#db2777","#ea580c","#16a34a","#64748b"];
export default function Home(){
 const [token,setToken]=useState(""); const [items,setItems]=useState<Expense[]>([]); const [summary,setSummary]=useState<Record<string,number>>({}); const [breakdown,setBreakdown]=useState<{days:any[];categories:any[]}>({days:[],categories:[]}); const [form,setForm]=useState({amount:"",description:"",category:"Другое"});
 const headers=()=>({Authorization:`tma ${token}`,"Content-Type":"application/json"});
 async function load(){if(!token)return; const [a,b,c]=await Promise.all([fetch(`${API}/expenses`,{headers:headers()}),fetch(`${API}/reports/summary`,{headers:headers()}),fetch(`${API}/reports/breakdown`,{headers:headers()})]); if(a.ok){setItems(await a.json());setSummary(await b.json());setBreakdown(await c.json())}}
 useEffect(()=>{load()},[token]);
 async function add(e:React.FormEvent){e.preventDefault();const r=await fetch(`${API}/expenses`,{method:"POST",headers:headers(),body:JSON.stringify({...form,amount:Number(form.amount)})});if(r.ok){setForm({amount:"",description:"",category:"Другое"});load()}}
 async function remove(id:number){if(confirm("Удалить эту трату?")){await fetch(`${API}/expenses/item/${id}`,{method:"DELETE",headers:headers()});load()}}
 async function edit(x:Expense){const amount=prompt("Сумма",String(x.amount));const description=prompt("Описание",x.description);if(!amount||!description)return;const category=prompt("Категория",x.category)||x.category;await fetch(`${API}/expenses/item/${x.id}`,{method:"PUT",headers:headers(),body:JSON.stringify({amount:Number(amount),description,category,currency:x.currency,spent_at:x.spent_at})});load()}
 if(!token)return <main className="auth"><h1>Мои расходы</h1><p>Войдите через Telegram — отдельный пароль не нужен.</p><TelegramLogin onAuth={setToken}/><details><summary>Локальная разработка</summary><input placeholder="Telegram initData" onChange={e=>setToken(e.target.value)}/></details></main>;
 return <main><header><div><h1>Мои расходы</h1><p>Ваш личный бюджет</p></div><button onClick={()=>setToken("")}>Выйти</button></header><section className="cards">{[["Сегодня",summary.today],["Неделя",summary.week],["Месяц",summary.month]].map(([k,v])=><article key={String(k)}><span>{k}</span><strong>{Number(v||0).toFixed(2)} TJS</strong></article>)}</section><section className="grid"><form onSubmit={add}><h2>Новая трата</h2><input required inputMode="decimal" placeholder="Сумма" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><input required placeholder="Описание" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["Другое","Еда","Транспорт","Дом","Здоровье","Покупки"].map(x=><option key={x}>{x}</option>)}</select><button>Добавить</button></form><article className="chart"><h2>По дням</h2><ResponsiveContainer width="100%" height={220}><BarChart data={breakdown.days}><Tooltip/><Bar dataKey="amount" fill="#2563eb" radius={6}/></BarChart></ResponsiveContainer></article><article className="chart"><h2>По категориям</h2><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={breakdown.categories} dataKey="amount" nameKey="category" outerRadius={80}>{breakdown.categories.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></article></section><section className="list"><div className="sectionHead"><h2>Все расходы</h2><a href={`${API}/expenses/export/csv`} onClick={e=>{if(!token)e.preventDefault()}}>CSV</a></div>{items.map(x=><article key={x.id}><div><strong>{x.description}</strong><span>{new Date(x.spent_at).toLocaleDateString("ru-RU")} · {x.category}</span></div><b>{x.amount} {x.currency}</b><button onClick={()=>edit(x)}>Изм.</button><button aria-label="Удалить" onClick={()=>remove(x.id)}>×</button></article>)}</section></main>
}
function TelegramLogin({onAuth}:{onAuth:(token:string)=>void}){useEffect(()=>{(window as any).onTelegramAuth=(user:any)=>onAuth(new URLSearchParams(Object.entries(user).map(([k,v])=>[k,String(v)])).toString());const s=document.createElement("script");s.src="https://telegram.org/js/telegram-widget.js?22";s.async=true;s.setAttribute("data-telegram-login",process.env.NEXT_PUBLIC_TELEGRAM_BOT_USERNAME||"");s.setAttribute("data-size","large");s.setAttribute("data-onauth","onTelegramAuth(user)");document.getElementById("telegram-login")?.appendChild(s);return()=>s.remove()},[onAuth]);return <div id="telegram-login"/>}
